# Generated by Django 5.2.5 on 2025-10-14 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_rename_salary_employee_basic_salary_and_more'),
        ('organization', '0002_menucategory_menuitem_usermenupermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('table_type', models.CharField(choices=[('employee_list', 'Employee List'), ('attendance_list', 'Attendance List'), ('leave_list', 'Leave List'), ('payroll_list', 'Payroll List'), ('custom', 'Custom Table')], max_length=50)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Model field name', max_length=100)),
                ('display_name', models.CharField(help_text='Column display name', max_length=200)),
                ('column_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('image', 'Image'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL'), ('json', 'JSON'), ('foreign_key', 'Foreign Key')], default='text', max_length=20)),
                ('width', models.CharField(blank=True, help_text="Column width (e.g., '150px')", max_length=10, null=True)),
                ('is_sortable', models.BooleanField(default=True)),
                ('is_searchable', models.BooleanField(default=True)),
                ('is_filterable', models.BooleanField(default=False)),
                ('default_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('css_class', models.CharField(blank=True, max_length=100, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='organization.dynamictable')),
            ],
            options={
                'ordering': ['order', 'field_name'],
                'unique_together': {('table', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='RoleTablePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('delete', 'Delete'), ('export', 'Export')], default='view', max_length=20)),
                ('can_access', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_permissions', to='organization.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_permissions', to='hrm.employeerole')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organization.dynamictable')),
            ],
            options={
                'ordering': ['role__name', 'table__name'],
                'unique_together': {('organization', 'role', 'table', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='RoleColumnPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('edit', 'Edit'), ('hide', 'Hide')], default='view', max_length=20)),
                ('can_access', models.BooleanField(default=True)),
                ('column_order', models.PositiveIntegerField(default=0, help_text='Custom order for this role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_permissions', to='organization.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_permissions', to='hrm.employeerole')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_permissions', to='organization.dynamictable')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='organization.tablecolumn')),
            ],
            options={
                'ordering': ['role__name', 'column_order'],
                'unique_together': {('organization', 'role', 'table', 'column', 'permission_type')},
            },
        ),
        migrations.CreateModel(
            name='UserTablePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_visibility', models.JSONField(default=dict, help_text='Column visibility settings')),
                ('column_order', models.JSONField(default=list, help_text='Custom column order')),
                ('page_size', models.PositiveIntegerField(default=20)),
                ('saved_filters', models.JSONField(default=dict, help_text='Saved filter configurations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_table_preferences', to='organization.organization')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='organization.dynamictable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization', 'table')},
            },
        ),
    ]
