# Generated by Django 5.2.5 on 2025-10-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0003_attendancedevice_attendanceholiday_attendancerecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='device_enrollment_id',
            field=models.CharField(blank=True, help_text='Enrollment ID from attendance device', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='device_user_id',
            field=models.CharField(blank=True, help_text='UID from attendance device', max_length=20, null=True),
        ),
    ]
