# Generated by Django 5.2.5 on 2025-10-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0004_employee_device_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancedevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='password',
            field=models.IntegerField(default=0, help_text='Device password (usually 0)'),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='platform',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='attendancedevice',
            name='timeout',
            field=models.IntegerField(default=10, help_text='Connection timeout in seconds'),
        ),
    ]
