# Generated by Django 3.2.8 on 2025-10-21 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_dynamictable_tablecolumn_roletablepermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hrm', '0005_attendancedevice_mac_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('holiday_type', models.CharField(blank=True, choices=[('governmental', 'Governmental'), ('official', 'Offical')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
            options={
                'verbose_name_plural': 'Holiday Calendar',
                'ordering': ['-id'],
            },
        ),
    ]
