# Generated by Django 5.2.7 on 2025-10-24 16:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0006_holidaycalendar'),
        ('organization', '0003_dynamictable_tablecolumn_roletablepermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeepayhead',
            options={'ordering': ['employee', 'payhead__display_order', '-effective_from'], 'verbose_name': 'Employee Payhead', 'verbose_name_plural': 'Employee Payheads'},
        ),
        migrations.AddField(
            model_name='employeepayhead',
            name='attendance_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='employeepayhead',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayhead',
            name='max_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeepayhead',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='employeepayhead',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_employee_payheads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepayhead',
            name='overtime_rate_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='employeepayhead',
            name='production_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='payhead',
            name='effective_from',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date from which this payhead is effective'),
        ),
        migrations.AddField(
            model_name='payhead',
            name='effective_to',
            field=models.DateField(blank=True, help_text='Date until which this payhead is effective', null=True),
        ),
        migrations.AddField(
            model_name='payhead',
            name='is_auto_calculated',
            field=models.BooleanField(default=True, help_text='Whether this payhead is automatically calculated'),
        ),
        migrations.AddField(
            model_name='payhead',
            name='is_gratuity_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payhead',
            name='max_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum amount limit', max_digits=12),
        ),
        migrations.AddField(
            model_name='payhead',
            name='max_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum percentage limit', max_digits=5),
        ),
        migrations.AddField(
            model_name='payhead',
            name='min_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum amount limit', max_digits=12),
        ),
        migrations.AddField(
            model_name='payhead',
            name='percentage_base',
            field=models.CharField(default='basic', help_text='Base for percentage calculation (basic, gross, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='payhead',
            name='production_rate_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Rate per unit for production-based calculation', max_digits=8),
        ),
        migrations.AddField(
            model_name='payhead',
            name='short_name',
            field=models.CharField(blank=True, help_text='Short name for display', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payhead',
            name='show_in_payslip',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='payhead',
            name='statutory_code',
            field=models.CharField(blank=True, help_text='Statutory code for compliance reporting', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeepayhead',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employee_payheads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payhead',
            name='calculation_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Basic'), ('attendance', 'Based on Attendance'), ('overtime', 'Based on Overtime'), ('production', 'Based on Production/Performance'), ('custom', 'Custom Calculation')], default='fixed', max_length=20),
        ),
        migrations.AddIndex(
            model_name='employeepayhead',
            index=models.Index(fields=['employee', 'is_active', 'effective_from'], name='hrm_employe_employe_707533_idx'),
        ),
        migrations.AddIndex(
            model_name='employeepayhead',
            index=models.Index(fields=['payhead', 'is_active'], name='hrm_employe_payhead_af44e7_idx'),
        ),
        migrations.AddIndex(
            model_name='payhead',
            index=models.Index(fields=['organization', 'is_active', 'payhead_type'], name='hrm_payhead_organiz_3f9abc_idx'),
        ),
        migrations.AddIndex(
            model_name='payhead',
            index=models.Index(fields=['organization', 'calculation_type', 'is_active'], name='hrm_payhead_organiz_b524bb_idx'),
        ),
    ]
