# Generated by Django 5.2.7 on 2025-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_alter_employeepayhead_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='employee',
        ),
        migrations.AddField(
            model_name='timetable',
            name='employees',
            field=models.ManyToManyField(related_name='timetables', to='hrm.employee'),
        ),
    ]
