# Generated by Django 5.2.7 on 2025-10-27 03:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0009_alter_branch_unique_together_and_more'),
        ('organization', '0003_dynamictable_tablecolumn_roletablepermission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendanceholiday',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendanceholiday',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'date'), name='unique_organization_attendance_holiday_when_not_deleted'),
        ),
    ]
