# Generated by Django 5.2.7 on 2025-10-24 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0007_alter_employeepayhead_options_and_more'),
        ('organization', '0003_dynamictable_tablecolumn_roletablepermission_and_more'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayslipComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=20)),
                ('component_name', models.CharField(max_length=200)),
                ('component_code', models.CharField(max_length=20)),
                ('calculation_type', models.CharField(default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('payhead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrm.payhead')),
                ('payslip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='payroll.payslip')),
            ],
            options={
                'ordering': ['component_type', 'display_order', 'component_name'],
            },
        ),
    ]
